import "./globals.css";
import type { Metadata } from "next";

import { Footer, NavBar } from "@/components";

export const metadata: Metadata = {
  title: "AiDios",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col xl:h-screen justify-between">
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
